### PR TITLE
Add patches for cabal-doctest-1.0.3 and doctest-0.13.0

### PR DESCRIPTION
**Pull request by RyanGlScott**

### CODE REVIEW

**Comment by hvr** [comment]
merged & update head.hackage; thanks!

**Comment by christiaanb** [comment]
Having the same issue here as with `singletons`:

```
[14 of 16] Compiling Runner           ( src/Runner.hs, dist/build/Runner.o )

src/Runner.hs:50:10: error:
    Not in scope: type constructor or class ‘Semigroup’
   |
50 | instance Semigroup Summary where
```

**Comment by RyanGlScott** [comment]
At least this one isn't directly my fault—I took this patch straight from https://github.com/hvr/head.hackage/pull/3 ;)

**Comment by RyanGlScott** [comment]
...never mind, I lied—I added the `Semigroup` instance _post facto_. My bad.

**Comment by hvr** [comment]
Should have been fixed up in dc0f7ac1ef486be7bffa7a7f3dc17c0c18c7fb65

**Comment by christiaanb** [comment]
Thanks, it works

**Pull request merged**
