### PR TITLE
Rip out old patches and cabal files

### PR DESCRIPTION
**Pull request by RyanGlScott**
`base-4.13` will feature more changes related to `MonadFail`. To make this migration easier on the `head.hackage` side, I'm opting to remove all existing `.patch` and `.cabal` files that relate to earlier `MonadFail` changes in some way, as they may possible complicate things going forward.

### CODE REVIEW

**Comment by phadej** [comment]
I’d write a small tool which would tell which patches do not correspond to the latest version on Hackage. That would help with GC. +/-?

**Comment by RyanGlScott** [comment]
Actually, @bgamari already contributed such a tool, which you can invoke with:

```
./scripts/patch-tool drop-old
```

That being said, this doesn't seem to catch old _`.cabal`_ files, which is a bit unfortunate.

**Comment by RyanGlScott** [comment]
Thankfully, it wasn't too difficult to adjust `patch-tool` to also catch old `.cabal` files. I've adjusted the scope of this PR to include every file that's out-of-date.

**Comment by RyanGlScott** [comment]
Let me know if keeping these commits separate is OK, or if you'd prefer that I squashed everything into a single commit.

**Comment by hvr** [comment]
The big purge has been done... :-)

**Comment by bgamari** [comment]
Ryan Scott <notifications@github.com> writes:

> Actually, @bgamari already contributed such a tool, which you can invoke with:
>
> ```
> ./scripts/patch-tool drop-old
> ```
>
> That being said, this doesn't seem to catch old _`.cabal`_ files, which is a bit unfortunate.
>
It would be quite straightforward to fix this.

**Comment by RyanGlScott** [comment]
@bgamari, way ahead of you :) https://github.com/hvr/head.hackage/pull/108#issuecomment-472010522 58c01ef746d366b850361a3a8f1daeb6eb1b1a33

**Pull request merged**
