### PR TITLE
hs-generate-overrides:  fix aeson

### PR DESCRIPTION
**Pull request by deepfire**
..which is missing `contravariant` in Nixpkgs `master`.

Described in https://github.com/hvr/head.hackage/issues/94

### CODE REVIEW

**Comment by phadej** [comment]
ping @mpickering 

I don't enough nix to comment, but why there's `ghc822`?

**Comment by deepfire** [comment]
@mpickering, done, thank you!  There's a bit too many ways to override both packages and package sets, I just can't seem to keep up! : -)

**Comment by mpickering** [comment]
Seems that the changes from #95 have also snuck in.

**Comment by hvr** [comment]
Thanks!

(@mpickering I assume you implied this PR was good to merge too)

**Pull request merged**
