### PR TITLE
Patch haskell-src-exts-1.20.2 for GHC 8.6.1

### PR DESCRIPTION
**Pull request by vaibhavsagar**
Not sure how this interacts with the existing `.cabal` file.

### CODE REVIEW

**Comment by mpickering** [comment]
This isn't necessary if the .cabal file is applied. Neither was the polyparse patch, sorry for the inconvenience I caused.

**Comment by vaibhavsagar** [comment]
No need to apologise! I'm surprised that the `polyparse` patch is unnecessary when there doesn't seem to be an override for it, how does that work?

**Comment by hvr** [comment]
@vaibhavsagar the `.cabal` files checked into head.hackage for `polyparse` and a couple others cheated by simply adding `-XNoMonadFailDesugaring` to the `ghc-options`; but that's not a proper solution, and it specifically it breaks down when you'd need exposed `MonadFail` instances as part of the exposed API of a such a package;

**Comment by vaibhavsagar** [comment]
I've made a PR including changes to the `.cabal` file at https://github.com/haskell-suite/haskell-src-exts/pull/413

**Pull request closed without merging**
