### PR TITLE
Properly handle .cabal files as well as patches (by mpickering)

### PR DESCRIPTION
**Pull request by deepfire**
cc @mpickering

### CODE REVIEW

**Comment by deepfire** [comment]
There is a problem with generation when _both_ `.cabal` and `.patch` are present, with the former taking precedence -- see an excerpt from generated `patches.nix`:

```
cabal-doctest = if super.cabal-doctest == null then super.cabal-doctest
else if super.cabal-doctest.version ==  "1.0.6"  then ( dontRevise( setCabalFile super.cabal-doctest /nix/store/r68sryv4gijn2dvgdnf3hcb0yvy8yl87-hs-generate-overrides-0.1-script/patches/patches/cabal-doctest-1.0.6.cabal ) )
else if super.cabal-doctest.version ==  "1.0.6"  then ( dontRevise( haskell.lib.appendPatch super.cabal-doctest /nix/store/r68sryv4gijn2dvgdnf3hcb0yvy8yl87-hs-generate-overrides-0.1-script/patches/patches/cabal-doctest-1.0.6.patch ) )
else
super.cabal-doctest
;
```

**Comment by deepfire** [comment]
Pushed a fix for the above problem.

**Comment by mpickering** [comment]
Thanks LGTM!

**Comment by hvr** [comment]
Thanks!

**Pull request merged**
