### PR TITLE
head.hackage.sh: Don't hardcode GHC path

### PR DESCRIPTION
**Pull request by bgamari**
I'd much prefer to simply specify the path on the command line.

### CODE REVIEW

**Comment by hvr** [comment]
fair enough; but do you also dislike having a default for GHC  if there's no global env-var already?

**Comment by hvr** [comment]
@bgamari I've merged this one before you add more commits to your master branch ;-)

**Comment by bgamari** [comment]
Herbert Valerio Riedel <notifications@github.com> writes:

> fair enough; but do you also dislike having a default for GHC  if there's no global env-var already?
>
In general I'm not a fan of having defaults that are applicable only on
a single person's machine.

**Comment by hvr** [comment]
@bgamari to be fair, it's not a single person's machine, it's for everyone using the ghc-head package from my ppa, which include Travis CI jobs ;-)

**Pull request merged**
